# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_history(object):
    def setupUi(self, history):
        history.setObjectName("history")
        history.resize(570, 500)
        self.lbl_history = QtWidgets.QLabel(history)
        self.lbl_history.setGeometry(QtCore.QRect(10, 10, 550, 400))
        self.lbl_history.setStyleSheet("background-color: white; \n"
"border: 2px solid black")
        self.lbl_history.setText("")
        self.lbl_history.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_history.setObjectName("lbl_history")
        self.pushButton = QtWidgets.QPushButton(history)
        self.pushButton.setGeometry(QtCore.QRect(10, 420, 550, 60))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(history)
        QtCore.QMetaObject.connectSlotsByName(history)

    def retranslateUi(self, history):
        _translate = QtCore.QCoreApplication.translate
        history.setWindowTitle(_translate("history", "История"))
        self.pushButton.setText(_translate("history", "Очистить историю"))
