# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_change_color.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win_change_color(object):
    def setupUi(self, win_change_color):
        win_change_color.setObjectName("win_change_color")
        win_change_color.resize(600, 300)
        self.label_2 = QtWidgets.QLabel(win_change_color)
        self.label_2.setGeometry(QtCore.QRect(290, 50, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(win_change_color)
        self.pushButton.setGeometry(QtCore.QRect(300, 180, 200, 60))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(win_change_color)
        self.widget.setGeometry(QtCore.QRect(20, 40, 191, 212))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_color = QtWidgets.QLabel(self.widget)
        self.lbl_color.setMinimumSize(QtCore.QSize(100, 30))
        self.lbl_color.setMaximumSize(QtCore.QSize(100, 30))
        self.lbl_color.setObjectName("lbl_color")
        self.verticalLayout.addWidget(self.lbl_color)
        self.rbt_black = QtWidgets.QRadioButton(self.widget)
        self.rbt_black.setMinimumSize(QtCore.QSize(160, 30))
        self.rbt_black.setMaximumSize(QtCore.QSize(160, 30))
        self.rbt_black.setChecked(True)
        self.rbt_black.setObjectName("rbt_black")
        self.verticalLayout.addWidget(self.rbt_black)
        self.rbt_red = QtWidgets.QRadioButton(self.widget)
        self.rbt_red.setMinimumSize(QtCore.QSize(160, 30))
        self.rbt_red.setMaximumSize(QtCore.QSize(160, 30))
        self.rbt_red.setObjectName("rbt_red")
        self.verticalLayout.addWidget(self.rbt_red)
        self.rbt_blue = QtWidgets.QRadioButton(self.widget)
        self.rbt_blue.setMinimumSize(QtCore.QSize(160, 30))
        self.rbt_blue.setMaximumSize(QtCore.QSize(160, 30))
        self.rbt_blue.setObjectName("rbt_blue")
        self.verticalLayout.addWidget(self.rbt_blue)
        self.rbt_orange = QtWidgets.QRadioButton(self.widget)
        self.rbt_orange.setMinimumSize(QtCore.QSize(160, 30))
        self.rbt_orange.setMaximumSize(QtCore.QSize(160, 30))
        self.rbt_orange.setObjectName("rbt_orange")
        self.verticalLayout.addWidget(self.rbt_orange)
        self.rbt_green = QtWidgets.QRadioButton(self.widget)
        self.rbt_green.setMinimumSize(QtCore.QSize(160, 30))
        self.rbt_green.setMaximumSize(QtCore.QSize(160, 30))
        self.rbt_green.setObjectName("rbt_green")
        self.verticalLayout.addWidget(self.rbt_green)

        self.retranslateUi(win_change_color)
        QtCore.QMetaObject.connectSlotsByName(win_change_color)

    def retranslateUi(self, win_change_color):
        _translate = QtCore.QCoreApplication.translate
        win_change_color.setWindowTitle(_translate("win_change_color", "Изменение цвета текста истории"))
        self.label_2.setText(_translate("win_change_color", "ТЕКСТ"))
        self.pushButton.setText(_translate("win_change_color", "Принять"))
        self.lbl_color.setText(_translate("win_change_color", "Цвета"))
        self.rbt_black.setText(_translate("win_change_color", "Чёрный"))
        self.rbt_red.setText(_translate("win_change_color", "Красный"))
        self.rbt_blue.setText(_translate("win_change_color", "Синий"))
        self.rbt_orange.setText(_translate("win_change_color", "Оранжевый"))
        self.rbt_green.setText(_translate("win_change_color", "Зелёный"))
