# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_about_proggram.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winProg(object):
    def setupUi(self, winProg):
        winProg.setObjectName("winProg")
        winProg.resize(500, 150)
        self.lbl_proggram = QtWidgets.QLabel(winProg)
        self.lbl_proggram.setGeometry(QtCore.QRect(10, 10, 480, 130))
        self.lbl_proggram.setAcceptDrops(False)
        self.lbl_proggram.setWordWrap(True)
        self.lbl_proggram.setObjectName("lbl_proggram")

        self.retranslateUi(winProg)
        QtCore.QMetaObject.connectSlotsByName(winProg)

    def retranslateUi(self, winProg):
        _translate = QtCore.QCoreApplication.translate
        winProg.setWindowTitle(_translate("winProg", "О программе"))
        self.lbl_proggram.setText(_translate("winProg", "Программа позволяет вам рассчитать стоимость партий товаров в магазине CorgiShop"))
