# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_about_author.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winAuthor(object):
    def setupUi(self, winAuthor):
        winAuthor.setObjectName("winAuthor")
        winAuthor.resize(500, 150)
        self.lbl_author = QtWidgets.QLabel(winAuthor)
        self.lbl_author.setGeometry(QtCore.QRect(10, 10, 480, 130))
        self.lbl_author.setAcceptDrops(False)
        self.lbl_author.setWordWrap(True)
        self.lbl_author.setObjectName("lbl_author")

        self.retranslateUi(winAuthor)
        QtCore.QMetaObject.connectSlotsByName(winAuthor)

    def retranslateUi(self, winAuthor):
        _translate = QtCore.QCoreApplication.translate
        winAuthor.setWindowTitle(_translate("winAuthor", "Об авторе"))
        self.lbl_author.setText(_translate("winAuthor", "Чтобы поддержать автора, вы можете перевести деньги по номеру +7-900-602-43-10 на Сбербанк или Тинькофф. Он очень хороший человек и любит корги"))
